name: Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        llvm-version:
          - 18.1.3
          - 18.1.2
          - 18.1.1
          - 17.0.6
        cmake-version:
          - 3.29.1
          - 3.29.0
          - 3.28.4
          - 3.28.3
        include:
          - llvm-version: 16.0.6
            cmake-version: 3.29.1
          - llvm-version: 15.0.7
            cmake-version: 3.29.1
          - llvm-version: 14.0.6
            cmake-version: 3.29.1
          - llvm-version: 13.0.1
            cmake-version: 3.29.1
      fail-fast: false
    runs-on: ubuntu-latest
    name: LLVM ${{ matrix.llvm-version }} - CMake ${{ matrix.cmake-version }}
    env:
      LLVM_VERSION: ${{ matrix.llvm-version }}
      CMAKE_VERSION: ${{ matrix.cmake-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: ./test.sh

      - name: Upload LLVM build
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ matrix.llvm-version }}-cmake-${{ matrix.cmake-version }}
          path: llvm-${{ matrix.llvm-version }}-cmake-${{ matrix.cmake-version }}.tar.gz

      - name: Upload LLVM build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ matrix.llvm-version }}-cmake-${{ matrix.cmake-version }}-build
          path: llvm-${{ matrix.llvm-version }}-cmake-${{ matrix.cmake-version }}-build.tar.gz
